services:
  doorcode-genie:
    build: .
    image: doorcode-genie
    container_name: doorcode-genie
    env_file: .env
    volumes:
      - doorcode-genie-logs:/var/log
      - .:/app
    restart: unless-stopped

volumes:
  doorcode-genie-logs:
